import SideBar from '@/components/SideBar'
import './globals.css'
import Header from '/components/Header'
import Head from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col'>
        <Header />
        <div className='flex h-full p-4 gap-x-4 grow'>
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  )
}
